# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "**/py.typed"

